Feature/authorization
MagzyCode/WorkoutGlobal pull request #2
Opened 2022-05-09 08:50 UTC by MagzyCode

2022-05-09 17:35 UTC, vliashko requested changes

2022-05-09 17:35 UTC, vliashko commented on WorkoutGlobal.Api/Controllers/AuthenticationController.cs
> +    [Route("api")]
Not correct global route.

2022-05-09 17:35 UTC, vliashko commented on WorkoutGlobal.Api/Controllers/AuthenticationController.cs
> +        [HttpPost("registrate")]
registrate - it's a verb, use 'registration' instead

2022-05-09 17:35 UTC, vliashko commented on WorkoutGlobal.Api/Controllers/AuthenticationController.cs
> +        /// Sets instance of authentication controller with AutoMapper instance.
Not only AutoMapper reference. It's a ctor, so best way to set summary 'Ctor for ...'. No need to describe hard thing

2022-05-09 17:35 UTC, vliashko commented on WorkoutGlobal.Api/Extensions/ServiceExtensions.cs
> +                o.User.RequireUniqueEmail = true;
No need for now to configure email some how.

2022-05-09 17:35 UTC, vliashko commented on WorkoutGlobal.Api/Migrations/20220506124830_Initial.cs
> +#pragma warning disable 1591
Why we need this? Or it auto-gen?

2022-05-09 17:35 UTC, vliashko commented on WorkoutGlobal.Api/Models/Validators/UserValidators/UserRegistrationDtoValidator.cs
> +                .NotEmpty()
Should we have NotNull && NotEmpty? If we remove NotNull will it allow nullable?

2022-05-09 17:35 UTC, vliashko commented on WorkoutGlobal.Api/Models/Validators/UserValidators/UserRegistrationDtoValidator.cs
> +                .Matches(@"[^\sА-Яа-я@%?#<>%/]")
Only latin alphabet

2022-05-09 17:35 UTC, vliashko commented on WorkoutGlobal.Api/Repositories/BaseRepositories/RepositoryManager.cs
>          /// Health repositoty instance.
'repositoty' -> 'repository '

2022-05-09 17:35 UTC, vliashko commented on WorkoutGlobal.UI/ApiConnection/Contracts/IAuthenticationService.cs
> +    public interface IAuthenticationService : IApiData
Why we need IAuthenticationService && IApiData? And why interface for contoller with name '...Service'

2022-05-09 21:57 UTC, MagzyCode commented on WorkoutGlobal.Api/Migrations/20220506124830_Initial.cs
> +#pragma warning disable 1591
No, it's auto-gen. I'm using it for disable xml-documentation for migrations. I want to use xml-documentation everywhere, except migrations.

2022-05-09 22:01 UTC, MagzyCode commented on WorkoutGlobal.Api/Models/Validators/UserValidators/UserRegistrationDtoValidator.cs
> +                .NotEmpty()
No. After reading the documentation on these methods, I made sure that the NotEmpty method also checks for null, so it's worth removing the data chain of the two methods.

2022-05-09 22:24 UTC, MagzyCode commented on WorkoutGlobal.UI/ApiConnection/Contracts/IAuthenticationService.cs
> +    public interface IAuthenticationService : IApiData
I'm using IApiData like limitation in generic class `WorkoutGlobal.UI.ApiConnection.Services.BaseService<T> where T : IApiData`. For me, classes and interfaces that provide access to the api come with the prefix "service". Maybe I'm inaccurate in naming the essence of the class.

2022-05-10 10:33 UTC, vliashko requested changes

2022-05-10 10:33 UTC, vliashko commented on WorkoutGlobal.UI/Middlewares/GlobalExceptionHandlerMiddleware.cs
> +                // TODO: Update this method for existed exceptions.
Need to finish this part.

2022-05-16 14:28 UTC, vliashko commented on WorkoutGlobal.Api.Tests/Controllers/AuthenticationControllerTests.cs
> +                .And.BeOfType<BadRequestObjectResult>()
At this point let put it as is. But in future let use separate part for this. 

result.Should().NotBeNull()
result.Sould().BeOfType<>() 
and so on..

2022-05-16 14:29 UTC, vliashko commented on WorkoutGlobal.Api.Tests/Repositories/AuthenticationRepositoryTests.cs
> +            _mapper
let configure mapper in contructor or initial class.

2022-05-16 14:32 UTC, vliashko commented on WorkoutGlobal.Api/Repositories/AuthorizationRepositories/AuthenticationRepository.cs
> +                .SingleOrDefault(user => user.UserName == userCredentialsDto.UserName);
Do not use .SingleOrDefault(user => user.UserName == userCredentialsDto.UserName);

Use .Where(user => user.UserName == userCredentialsDto.UserName).SingleOrDefault()

That can up some memory allocation, but better from timing site

2022-05-17 06:54 UTC, MagzyCode commented on WorkoutGlobal.Api/Controllers/AuthenticationController.cs
> +                    Details = new StackTrace().ToString()
Common stack trace of call.

2022-05-17 19:09 UTC, vliashko approved these changes
Looks good!

2022-05-17 21:17 UTC, merged