Create main integration tests.
MagzyCode/WorkoutGlobal pull request #6
Opened 2022-07-08 15:11 UTC by MagzyCode

2022-07-11 06:17 UTC, vliashko requested changes

2022-07-11 06:17 UTC, vliashko commented on WorkoutGlobal.Api.IntegrationTests/Controllers/AuthenticationControllerIntegrationTests.cs
> +        private readonly List<string> _purgeList = new();
Let's make some base class for all of variables

2022-07-11 06:17 UTC, vliashko commented on WorkoutGlobal.Api.IntegrationTests/Controllers/AuthenticationControllerIntegrationTests.cs
> +            var createdUserCredentialId = registrationResponse.Content.ReadAsStringAsync().Result.Replace("\"", "");
Do not use .Result, use await.

Do not use any hardcode replace, use System.Text.Json to work with Content (or Newtonsoft)

2022-07-11 06:17 UTC, vliashko commented on WorkoutGlobal.Api.IntegrationTests/Controllers/UserCredentialsControllerIntegrationTests.cs
> +            createdUser!.UserName.Should().Be("ChangeValue");
Let's not use '!'

2022-07-11 06:17 UTC, vliashko commented on WorkoutGlobal.Api/Repositories/AuthorizationRepositories/AuthenticationRepository.cs
> +        public async Task Purge(UserCredentials userCredentials)
No need to create another method for service / repo. Add parameter for classic delete (bool isPurge = false), and work with it

2022-07-11 06:17 UTC, vliashko commented on WorkoutGlobal.Api/Filters/DocumentationFilter/SwaggerEndpointsFilter.cs
> +    public class SwaggerEndpointsFilter : IDocumentFilter
Can we use attribute [ApiExplorerSettings(IgnoreApi = true)] instead of custom?

2022-07-11 11:32 UTC, MagzyCode commented on WorkoutGlobal.Api.IntegrationTests/Controllers/AuthenticationControllerIntegrationTests.cs
> +        private readonly List<string> _purgeList = new();
Create base class for all needed fields.

2022-07-11 11:34 UTC, MagzyCode commented on WorkoutGlobal.Api.IntegrationTests/Controllers/AuthenticationControllerIntegrationTests.cs
> +            var createdUserCredentialId = registrationResponse.Content.ReadAsStringAsync().Result.Replace("\"", "");
Replace all `.Result` on using `async/await`. Instead of using `string.Replace` change method from `ReadAsStringAsync()` to `ReadFromJsonAsync<string>()`.

2022-07-11 11:35 UTC, MagzyCode commented on WorkoutGlobal.Api.IntegrationTests/Controllers/UserCredentialsControllerIntegrationTests.cs
> +            createdUser!.UserName.Should().Be("ChangeValue");
Delete all `!`.

2022-07-11 11:37 UTC, MagzyCode commented on WorkoutGlobal.Api/Repositories/AuthorizationRepositories/AuthenticationRepository.cs
> +        public async Task Purge(UserCredentials userCredentials)
Delete purge methods in repos. But using basic delete method of repos, because didn't find a use for `isPurge` param.

2022-07-11 11:38 UTC, MagzyCode commented on WorkoutGlobal.Api/Filters/DocumentationFilter/SwaggerEndpointsFilter.cs
> +    public class SwaggerEndpointsFilter : IDocumentFilter
Yes, we can. Use this custom attribute for hiding purge-endpoints.

2022-07-18 11:48 UTC, vliashko approved these changes

2022-07-18 12:35 UTC, merged